resources:
- ../base

patches:
- target:
    kind: Namespace
    name: dev-ns
  patch: |-
    - op: replace
      path: /metadata/name
      value: cert-manager
    - op: replace
      path: /metadata/labels/owner
      value: GCP-Team-Dev